using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using PactNet;
using PactNet.Verifier;
using UserService.Controllers;
using UserService.Data;
using UserService.Models;
using Xunit;
using Xunit.Abstractions;

namespace ContractTests.Provider;

/// <summary>
/// Provider-side Pact verification for UserService.
///
/// Reads the pact file generated by OrderConsumerTests and verifies that the real
/// UserService implementation satisfies every interaction defined in that contract.
///
/// Starts UserService on a real Kestrel TCP port because PactNet 5.x uses a
/// Rust-based verifier that makes actual network connections. The in-process
/// TestServer transport used by WebApplicationFactory is not reachable over TCP.
/// </summary>
public class UserProviderTests : IAsyncLifetime
{
    private readonly ITestOutputHelper _output;
    private WebApplication? _app;
    private Uri _serverUri = null!;

    public UserProviderTests(ITestOutputHelper output)
    {
        _output = output;
    }

    public async Task InitializeAsync()
    {
        int port = GetFreePort();
        _serverUri = new Uri($"http://127.0.0.1:{port}");

        var builder = WebApplication.CreateBuilder();
        builder.WebHost.UseUrls($"http://127.0.0.1:{port}");

        // Register controllers from the UserService assembly
        builder.Services
            .AddControllers()
            .AddApplicationPart(typeof(UsersController).Assembly);

        // Use in-memory DB instead of SQL Server
        builder.Services.AddDbContext<UserDbContext>(opt =>
            opt.UseInMemoryDatabase("PactTestDb"));

        _app = builder.Build();
        _app.MapControllers();

        // Seed the user that the consumer pact references
        using (var scope = _app.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<UserDbContext>();
            db.Database.EnsureCreated();
            if (!db.Users.Any())
            {
                db.Users.Add(new User
                {
                    Id = new Guid("11111111-1111-1111-1111-111111111111"),
                    Name = "Alice",
                    Email = "alice@example.com",
                    CreatedAt = DateTime.SpecifyKind(new DateTime(2024, 1, 1, 0, 0, 0), DateTimeKind.Utc)
                });
                db.SaveChanges();
            }
        }

        await _app.StartAsync();
    }

    [Fact]
    public void UserService_SatisfiesPactWith_OrderService()
    {
        var pactFile = Path.Combine(
            Directory.GetCurrentDirectory(),
            "..", "..", "..", "pacts",
            "order-service-user-service.json");

        Assert.True(File.Exists(pactFile),
            $"Pact file not found at {pactFile}. Run OrderConsumerTests first to generate it.");

        var config = new PactVerifierConfig
        {
            LogLevel = PactLogLevel.Debug
        };
        var verifier = new PactVerifier("user-service", config);

        verifier
            .WithHttpEndpoint(_serverUri)
            .WithFileSource(new FileInfo(pactFile))
            .Verify();
    }

    public async Task DisposeAsync()
    {
        if (_app is not null)
        {
            await _app.StopAsync();
            await _app.DisposeAsync();
        }
    }

    private static int GetFreePort()
    {
        using var l = new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback, 0);
        l.Start();
        int port = ((System.Net.IPEndPoint)l.LocalEndpoint).Port;
        l.Stop();
        return port;
    }
}
