using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using PactNet;
using PactNet.Verifier;
using UserService.Data;
using UserService.Models;
using Xunit;
using Xunit.Abstractions;

namespace ContractTests.Provider;

/// <summary>
/// Provider-side Pact verification for UserService.
///
/// Reads the pact file generated by OrderConsumerTests and verifies that the real
/// UserService implementation satisfies every interaction defined in that contract.
///
/// Uses WebApplicationFactory to spin up UserService in-process with an EF Core
/// in-memory database seeded with known test data.
/// </summary>
public class UserProviderTests : IClassFixture<WebApplicationFactory<UserService.Program>>, IDisposable
{
    private readonly WebApplicationFactory<UserService.Program> _factory;
    private readonly ITestOutputHelper _output;

    public UserProviderTests(WebApplicationFactory<UserService.Program> factory, ITestOutputHelper output)
    {
        _output = output;

        // Override DB with in-memory + seed the known user id used in consumer pact
        _factory = factory.WithWebHostBuilder(builder =>
        {
            builder.ConfigureServices(services =>
            {
                // Remove real SQL Server registration
                var descriptor = services.SingleOrDefault(d =>
                    d.ServiceType == typeof(DbContextOptions<UserDbContext>));
                if (descriptor is not null) services.Remove(descriptor);

                services.AddDbContext<UserDbContext>(opt =>
                    opt.UseInMemoryDatabase("PactTestDb"));

                // Seed the user that the consumer pact references
                var sp = services.BuildServiceProvider();
                using var scope = sp.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<UserDbContext>();
                db.Database.EnsureCreated();
                if (!db.Users.Any())
                {
                    db.Users.Add(new User
                    {
                        Id = new Guid("11111111-1111-1111-1111-111111111111"),
                        Name = "Alice",
                        Email = "alice@example.com",
                        CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                    });
                    db.SaveChanges();
                }
            });
        });
    }

    [Fact]
    public void UserService_SatisfiesPactWith_OrderService()
    {
        var pactFile = Path.Combine(
            Directory.GetCurrentDirectory(),
            "..", "..", "..", "pacts",
            "order-service-user-service.json");

        Assert.True(File.Exists(pactFile),
            $"Pact file not found at {pactFile}. Run OrderConsumerTests first to generate it.");

        using var server = _factory.Server;
        var verifier = new PactVerifier("user-service", new PactVerifierConfig());

        verifier
            .WithHttpEndpoint(server.BaseAddress)
            .WithFileSource(new FileInfo(pactFile))
            .Verify();
    }

    public void Dispose() => _factory.Dispose();
}
